# Generated by Django 3.0.8 on 2020-07-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.CharField(max_length=200)),
                ('password', models.EmailField(max_length=200)),
                ('cars', models.CharField(max_length=200)),
            ],
        ),
    ]
